name: Build and Release DEB

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'    # 当你推送 v1.0.0 等 tag 时，也触发构建
  workflow_dispatch:  # 手动运行也支持

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          brew install ldid dpkg

      - name: Build deb
        run: |
          make clean package FINALPACKAGE=1

      - name: Upload DEB to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ./packages/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
