name: Build and Release DEB

on:
  push:
    tags:
      - 'v*.*.*'  # 仅在推送 tag（如 v1.0.0）时触发
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          brew install ldid dpkg

      - name: Build deb
        run: |
          make clean package FINALPACKAGE=1

      - name: Upload DEB to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./packages/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
